version: '3.7'

services:
 cmdline-dev:
  build:
   context: . 
  working_dir: /app
  volumes:
   - "../:/app"
  command: sleep infinity
 postgresql:
  image: postgres:13.3
  restart: always
  environment: 
   POSTGRES_PASSWORD: admin1324
